version: '3.7'
services:
  mongo:
    image: 'mongo:latest'
    restart: unless-stopped
    ports:
      - ${MONGO_PORT}:27017
    env_file:
      - .env
    volumes:
      - ./data:/data/db

  server:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mongo
    env_file:
      - .env
    expose:
      - ${PORT}
    ports:
      - 8000:8000
    volumes:
      - /app/node_modules
      - ./src:/app/src
